"""A simple PDF document generator built with Streamlit.

Concepts this app demonstrates (useful as a teaching checklist):
  1. Building a PDF in memory with reportlab -- no temp files on disk.
  2. io.BytesIO -- an in-memory "file" that libraries expecting a file
     object can write to directly.
  3. st.download_button -- serving generated bytes to the user's browser
     as a downloadable file.
  4. st.session_state used to hold a growable list of content blocks
     (same list-in-session-state pattern as the to-do list and expense
     tracker projects).
  5. Basic widgets: text_input, text_area, selectbox, columns.

Run it with:  streamlit run app.py
"""
import io

import streamlit as st
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem

BLOCK_TYPES = ["Paragraph", "Bullet list", "Heading"]

if "blocks" not in st.session_state:
    st.session_state.blocks = []

st.set_page_config(page_title="PDF Generator", page_icon="📄")
st.title("📄 PDF Generator")
st.caption("Build a simple document from title + content blocks, then download it as a PDF.")

# ---- document title / author ----
col1, col2 = st.columns(2)
with col1:
    doc_title = st.text_input("Document title", value="My Document")
with col2:
    doc_author = st.text_input("Author", value="")

st.divider()

# ---- add a content block ----
st.subheader("Add a content block")
with st.form("add_block_form", clear_on_submit=True):
    block_type = st.selectbox("Block type", BLOCK_TYPES)
    # A single, statically-labelled, fixed-key widget -- widgets inside a
    # form don't rerun when another field (like block_type above) changes,
    # so a label/placeholder that depended on block_type would silently
    # swap the widget's identity out from under whatever the user had
    # already typed, the moment they finally hit submit. See the mentoring
    # guide for a worked example of this exact bug.
    text = st.text_area(
        "Text",
        placeholder="A paragraph or heading's text, or one bullet item per line for a bullet list",
        key="block_text",
    )
    submitted = st.form_submit_button("Add block")

    if submitted and text.strip():
        st.session_state.blocks.append({"type": block_type, "text": text.strip()})

st.divider()

# ---- preview + reorder/delete ----
st.subheader("Blocks in this document")
if not st.session_state.blocks:
    st.info("No content blocks yet -- add one above.")

for i, block in enumerate(st.session_state.blocks):
    col_text, col_delete = st.columns([5, 1])
    with col_text:
        st.markdown(f"**{block['type']}**")
        st.write(block["text"])
    with col_delete:
        if st.button("🗑️", key=f"delete_{i}"):
            st.session_state.blocks.pop(i)
            st.rerun()

st.divider()


def build_pdf(title, author, blocks):
    """Build the PDF entirely in memory and return the raw bytes."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=2.2 * cm, rightMargin=2.2 * cm, topMargin=2 * cm, bottomMargin=2 * cm,
        title=title,
    )
    styles = getSampleStyleSheet()
    story = [Paragraph(title, styles["Title"])]
    if author:
        story.append(Paragraph(f"by {author}", styles["Normal"]))
    story.append(Spacer(1, 0.8 * cm))

    for block in blocks:
        if block["type"] == "Heading":
            story.append(Paragraph(block["text"], styles["Heading2"]))
        elif block["type"] == "Bullet list":
            items = [line.strip() for line in block["text"].splitlines() if line.strip()]
            story.append(ListFlowable(
                [ListItem(Paragraph(item, styles["Normal"])) for item in items],
                bulletType="bullet",
            ))
        else:
            story.append(Paragraph(block["text"], styles["Normal"]))
        story.append(Spacer(1, 0.4 * cm))

    doc.build(story)
    return buffer.getvalue()


# ---- generate + download ----
st.subheader("Download")
pdf_bytes = build_pdf(doc_title or "Untitled", doc_author, st.session_state.blocks)
st.download_button(
    "⬇️ Download PDF",
    data=pdf_bytes,
    file_name=f"{(doc_title or 'document').strip().replace(' ', '_')}.pdf",
    mime="application/pdf",
)
st.caption(f"{len(pdf_bytes):,} bytes, {len(st.session_state.blocks)} content block(s)")
